### ISSUE TITLE
What's your opinion on the addition of ActiveRecord::Relation#or?

### ISSUE THREAD

**Issue by aj-foster** [olivierlacan/ask#4]
A few days ago, the "or" query was added to rails/rails master (here is the pull request: https://github.com/rails/rails/pull/16052).

As a math person, I've been awaiting this. The query DSL seemed incomplete without it, and there have been a handful of times when it might have proved useful. I'm curious to know your opinion about it, however: Is it a good addition? Is its addition going to encourage people to write overly-complicated / inefficient / unnecessary queries?

Thanks; hope you are doing well.

**Comment by olivierlacan** [comment]
Oh I'm sorry I totally missed this.

**Comment by olivierlacan** [comment]
I think it's a great additionally functionality-wise. But I find the interface quite ugly. It seems very odd to me to write: 

``` ruby
User.where.not(updated_at: nil)
```

Even something as seemingly ugly as this would make more sense to me: 

``` ruby
User.where_not(updated_at: nil)
```

Or even: 

``` ruby
User.where(:not, updated_at: nil)
```

Of course it's easy to blabber about fancy interfaces when you're not the one who has to deal with all the legacy interactions and accepted inputs for the `where` method. I think there were some interesting ideas for ORM interfaces in https://github.com/activerecord-hackery/squeel and http://rom-rb.org/learn/ but ultimately ActiveRecord works fine for 80-90% of the cases and I have no qualms in dropping down to raw SQL and passing strings to `AR#where`.
